/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HTTPValidationError } from '../models/index'
import { HTTPValidationErrorFromJSON, HTTPValidationErrorToJSON } from '../models/index'
import * as runtime from '../runtime'

export interface GithubAuthAuthGithubGetRequest {
  returnUrl?: string | null
}

export interface GithubCallbackAuthCallbackGetRequest {
  code?: string | null
  state?: string | null
}

export interface LoginPageAuthLoginGetRequest {
  returnUrl?: string | null
  error?: string | null
}

export interface LogoutAuthLogoutGetRequest {
  returnUrl?: string | null
}

export interface VerifyTokenAuthVerifyGetRequest {
  token?: string | null
  tensorsSession?: string | null
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Show success page after login.
   * Auth Success
   */
  async authSuccessAuthSuccessGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const urlPath = `/auth/success`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Show success page after login.
   * Auth Success
   */
  async authSuccessAuthSuccessGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.authSuccessAuthSuccessGetRaw(initOverrides)
    return await response.value()
  }

  /**
   * Redirect to GitHub OAuth.
   * Github Auth
   */
  async githubAuthAuthGithubGetRaw(
    requestParameters: GithubAuthAuthGithubGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    const queryParameters: any = {}

    if (requestParameters['returnUrl'] != null) {
      queryParameters['return_url'] = requestParameters['returnUrl']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const urlPath = `/auth/github`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Redirect to GitHub OAuth.
   * Github Auth
   */
  async githubAuthAuthGithubGet(
    requestParameters: GithubAuthAuthGithubGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.githubAuthAuthGithubGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Handle GitHub OAuth callback.
   * Github Callback
   */
  async githubCallbackAuthCallbackGetRaw(
    requestParameters: GithubCallbackAuthCallbackGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    const queryParameters: any = {}

    if (requestParameters['code'] != null) {
      queryParameters['code'] = requestParameters['code']
    }

    if (requestParameters['state'] != null) {
      queryParameters['state'] = requestParameters['state']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const urlPath = `/auth/callback`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Handle GitHub OAuth callback.
   * Github Callback
   */
  async githubCallbackAuthCallbackGet(
    requestParameters: GithubCallbackAuthCallbackGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.githubCallbackAuthCallbackGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Show login page.
   * Login Page
   */
  async loginPageAuthLoginGetRaw(
    requestParameters: LoginPageAuthLoginGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    const queryParameters: any = {}

    if (requestParameters['returnUrl'] != null) {
      queryParameters['return_url'] = requestParameters['returnUrl']
    }

    if (requestParameters['error'] != null) {
      queryParameters['error'] = requestParameters['error']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const urlPath = `/auth/login`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Show login page.
   * Login Page
   */
  async loginPageAuthLoginGet(
    requestParameters: LoginPageAuthLoginGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.loginPageAuthLoginGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Clear session and redirect.
   * Logout
   */
  async logoutAuthLogoutGetRaw(
    requestParameters: LogoutAuthLogoutGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    const queryParameters: any = {}

    if (requestParameters['returnUrl'] != null) {
      queryParameters['return_url'] = requestParameters['returnUrl']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const urlPath = `/auth/logout`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Clear session and redirect.
   * Logout
   */
  async logoutAuthLogoutGet(
    requestParameters: LogoutAuthLogoutGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.logoutAuthLogoutGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Verify a session token. Returns user info if valid.
   * Verify Token
   */
  async verifyTokenAuthVerifyGetRaw(
    requestParameters: VerifyTokenAuthVerifyGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    const queryParameters: any = {}

    if (requestParameters['token'] != null) {
      queryParameters['token'] = requestParameters['token']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const urlPath = `/auth/verify`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Verify a session token. Returns user info if valid.
   * Verify Token
   */
  async verifyTokenAuthVerifyGet(
    requestParameters: VerifyTokenAuthVerifyGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.verifyTokenAuthVerifyGetRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
