/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GithubAuthAuthGithubGetRequest {
    returnUrl?: string | null;
}

export interface GithubCallbackAuthCallbackGetRequest {
    code?: string | null;
    state?: string | null;
}

export interface LoginPageAuthLoginGetRequest {
    returnUrl?: string | null;
    error?: string | null;
}

export interface LogoutAuthLogoutGetRequest {
    returnUrl?: string | null;
}

export interface VerifyTokenAuthVerifyGetRequest {
    token?: string | null;
    tensorsSession?: string | null;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authSuccessAuthSuccessGet without sending the request
     */
    async authSuccessAuthSuccessGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/success`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show success page after login.
     * Auth Success
     */
    async authSuccessAuthSuccessGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.authSuccessAuthSuccessGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Show success page after login.
     * Auth Success
     */
    async authSuccessAuthSuccessGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.authSuccessAuthSuccessGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for githubAuthAuthGithubGet without sending the request
     */
    async githubAuthAuthGithubGetRequestOpts(requestParameters: GithubAuthAuthGithubGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['returnUrl'] != null) {
            queryParameters['return_url'] = requestParameters['returnUrl'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/github`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Redirect to GitHub OAuth.
     * Github Auth
     */
    async githubAuthAuthGithubGetRaw(requestParameters: GithubAuthAuthGithubGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.githubAuthAuthGithubGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Redirect to GitHub OAuth.
     * Github Auth
     */
    async githubAuthAuthGithubGet(requestParameters: GithubAuthAuthGithubGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.githubAuthAuthGithubGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for githubCallbackAuthCallbackGet without sending the request
     */
    async githubCallbackAuthCallbackGetRequestOpts(requestParameters: GithubCallbackAuthCallbackGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/callback`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Handle GitHub OAuth callback.
     * Github Callback
     */
    async githubCallbackAuthCallbackGetRaw(requestParameters: GithubCallbackAuthCallbackGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.githubCallbackAuthCallbackGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handle GitHub OAuth callback.
     * Github Callback
     */
    async githubCallbackAuthCallbackGet(requestParameters: GithubCallbackAuthCallbackGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.githubCallbackAuthCallbackGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginPageAuthLoginGet without sending the request
     */
    async loginPageAuthLoginGetRequestOpts(requestParameters: LoginPageAuthLoginGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['returnUrl'] != null) {
            queryParameters['return_url'] = requestParameters['returnUrl'];
        }

        if (requestParameters['error'] != null) {
            queryParameters['error'] = requestParameters['error'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show login page.
     * Login Page
     */
    async loginPageAuthLoginGetRaw(requestParameters: LoginPageAuthLoginGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.loginPageAuthLoginGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Show login page.
     * Login Page
     */
    async loginPageAuthLoginGet(requestParameters: LoginPageAuthLoginGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.loginPageAuthLoginGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logoutAuthLogoutGet without sending the request
     */
    async logoutAuthLogoutGetRequestOpts(requestParameters: LogoutAuthLogoutGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['returnUrl'] != null) {
            queryParameters['return_url'] = requestParameters['returnUrl'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Clear session and redirect.
     * Logout
     */
    async logoutAuthLogoutGetRaw(requestParameters: LogoutAuthLogoutGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.logoutAuthLogoutGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Clear session and redirect.
     * Logout
     */
    async logoutAuthLogoutGet(requestParameters: LogoutAuthLogoutGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.logoutAuthLogoutGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyTokenAuthVerifyGet without sending the request
     */
    async verifyTokenAuthVerifyGetRequestOpts(requestParameters: VerifyTokenAuthVerifyGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/verify`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Verify a session token. Returns user info if valid.
     * Verify Token
     */
    async verifyTokenAuthVerifyGetRaw(requestParameters: VerifyTokenAuthVerifyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.verifyTokenAuthVerifyGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Verify a session token. Returns user info if valid.
     * Verify Token
     */
    async verifyTokenAuthVerifyGet(requestParameters: VerifyTokenAuthVerifyGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.verifyTokenAuthVerifyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
