/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetModelApiCivitaiModelModelIdGetRequest {
    modelId: number;
}

/**
 * 
 */
export class CivitAIApi extends runtime.BaseAPI {

    /**
     * Creates request options for getModelApiCivitaiModelModelIdGet without sending the request
     */
    async getModelApiCivitaiModelModelIdGetRequestOpts(requestParameters: GetModelApiCivitaiModelModelIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling getModelApiCivitaiModelModelIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["api_key"] = await this.configuration.apiKey("api_key"); // APIKeyQuery authentication
        }


        let urlPath = `/api/civitai/model/{model_id}`;
        urlPath = urlPath.replace(`{${"model_id"}}`, encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get model details from CivitAI and cache to database.
     * Get Model
     */
    async getModelApiCivitaiModelModelIdGetRaw(requestParameters: GetModelApiCivitaiModelModelIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getModelApiCivitaiModelModelIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get model details from CivitAI and cache to database.
     * Get Model
     */
    async getModelApiCivitaiModelModelIdGet(requestParameters: GetModelApiCivitaiModelModelIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getModelApiCivitaiModelModelIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
