/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  GenerateRequest,
  GenerateResponse,
  HTTPValidationError,
  ModelsResponse,
  QueueStatusResponse,
  SystemStatsResponse,
  WorkflowRequest,
  WorkflowResponse,
} from '../models/index'
import {
  GenerateRequestFromJSON,
  GenerateRequestToJSON,
  GenerateResponseFromJSON,
  GenerateResponseToJSON,
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
  ModelsResponseFromJSON,
  ModelsResponseToJSON,
  QueueStatusResponseFromJSON,
  QueueStatusResponseToJSON,
  SystemStatsResponseFromJSON,
  SystemStatsResponseToJSON,
  WorkflowRequestFromJSON,
  WorkflowRequestToJSON,
  WorkflowResponseFromJSON,
  WorkflowResponseToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface ComfyuiGenerateApiComfyuiGeneratePostRequest {
  generateRequest: GenerateRequest
}

export interface ComfyuiHistoryDetailApiComfyuiHistoryPromptIdGetRequest {
  promptId: string
}

export interface ComfyuiHistoryListApiComfyuiHistoryGetRequest {
  limit?: number
}

export interface ComfyuiImageApiComfyuiImageFilenameGetRequest {
  filename: string
  subfolder?: string
  folderType?: string
}

export interface ComfyuiWorkflowApiComfyuiWorkflowPostRequest {
  workflowRequest: WorkflowRequest
}

/**
 *
 */
export class ComfyUIAPIApi extends runtime.BaseAPI {
  /**
   * Clear the ComfyUI queue.
   * Comfyui Clear Queue
   */
  async comfyuiClearQueueApiComfyuiQueueDeleteRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/comfyui/queue`

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Clear the ComfyUI queue.
   * Comfyui Clear Queue
   */
  async comfyuiClearQueueApiComfyuiQueueDelete(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.comfyuiClearQueueApiComfyuiQueueDeleteRaw(initOverrides)
    return await response.value()
  }

  /**
   * Generate an image using a simple text-to-image workflow.  This uses the built-in SDXL/Flux compatible workflow template. For custom workflows, use the /workflow endpoint instead.
   * Comfyui Generate
   */
  async comfyuiGenerateApiComfyuiGeneratePostRaw(
    requestParameters: ComfyuiGenerateApiComfyuiGeneratePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GenerateResponse>> {
    if (requestParameters['generateRequest'] == null) {
      throw new runtime.RequiredError(
        'generateRequest',
        'Required parameter "generateRequest" was null or undefined when calling comfyuiGenerateApiComfyuiGeneratePost().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/comfyui/generate`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: GenerateRequestToJSON(requestParameters['generateRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => GenerateResponseFromJSON(jsonValue))
  }

  /**
   * Generate an image using a simple text-to-image workflow.  This uses the built-in SDXL/Flux compatible workflow template. For custom workflows, use the /workflow endpoint instead.
   * Comfyui Generate
   */
  async comfyuiGenerateApiComfyuiGeneratePost(
    requestParameters: ComfyuiGenerateApiComfyuiGeneratePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GenerateResponse> {
    const response = await this.comfyuiGenerateApiComfyuiGeneratePostRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Get details for a specific history entry.
   * Comfyui History Detail
   */
  async comfyuiHistoryDetailApiComfyuiHistoryPromptIdGetRaw(
    requestParameters: ComfyuiHistoryDetailApiComfyuiHistoryPromptIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    if (requestParameters['promptId'] == null) {
      throw new runtime.RequiredError(
        'promptId',
        'Required parameter "promptId" was null or undefined when calling comfyuiHistoryDetailApiComfyuiHistoryPromptIdGet().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    let urlPath = `/api/comfyui/history/{prompt_id}`
    urlPath = urlPath.replace(
      `{${'prompt_id'}}`,
      encodeURIComponent(String(requestParameters['promptId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Get details for a specific history entry.
   * Comfyui History Detail
   */
  async comfyuiHistoryDetailApiComfyuiHistoryPromptIdGet(
    requestParameters: ComfyuiHistoryDetailApiComfyuiHistoryPromptIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.comfyuiHistoryDetailApiComfyuiHistoryPromptIdGetRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * List ComfyUI generation history.
   * Comfyui History List
   */
  async comfyuiHistoryListApiComfyuiHistoryGetRaw(
    requestParameters: ComfyuiHistoryListApiComfyuiHistoryGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    const queryParameters: any = {}

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/comfyui/history`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * List ComfyUI generation history.
   * Comfyui History List
   */
  async comfyuiHistoryListApiComfyuiHistoryGet(
    requestParameters: ComfyuiHistoryListApiComfyuiHistoryGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.comfyuiHistoryListApiComfyuiHistoryGetRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Fetch a generated image from ComfyUI.  Use this to retrieve images by filename after generation.
   * Comfyui Image
   */
  async comfyuiImageApiComfyuiImageFilenameGetRaw(
    requestParameters: ComfyuiImageApiComfyuiImageFilenameGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['filename'] == null) {
      throw new runtime.RequiredError(
        'filename',
        'Required parameter "filename" was null or undefined when calling comfyuiImageApiComfyuiImageFilenameGet().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['subfolder'] != null) {
      queryParameters['subfolder'] = requestParameters['subfolder']
    }

    if (requestParameters['folderType'] != null) {
      queryParameters['folder_type'] = requestParameters['folderType']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    let urlPath = `/api/comfyui/image/{filename}`
    urlPath = urlPath.replace(
      `{${'filename'}}`,
      encodeURIComponent(String(requestParameters['filename'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Fetch a generated image from ComfyUI.  Use this to retrieve images by filename after generation.
   * Comfyui Image
   */
  async comfyuiImageApiComfyuiImageFilenameGet(
    requestParameters: ComfyuiImageApiComfyuiImageFilenameGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.comfyuiImageApiComfyuiImageFilenameGetRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * List available models in ComfyUI.
   * Comfyui Models
   */
  async comfyuiModelsApiComfyuiModelsGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ModelsResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/comfyui/models`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => ModelsResponseFromJSON(jsonValue))
  }

  /**
   * List available models in ComfyUI.
   * Comfyui Models
   */
  async comfyuiModelsApiComfyuiModelsGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ModelsResponse> {
    const response = await this.comfyuiModelsApiComfyuiModelsGetRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get ComfyUI queue status.
   * Comfyui Queue
   */
  async comfyuiQueueApiComfyuiQueueGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<QueueStatusResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/comfyui/queue`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      QueueStatusResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get ComfyUI queue status.
   * Comfyui Queue
   */
  async comfyuiQueueApiComfyuiQueueGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<QueueStatusResponse> {
    const response = await this.comfyuiQueueApiComfyuiQueueGetRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get ComfyUI system stats (GPU, RAM, etc.).
   * Comfyui Status
   */
  async comfyuiStatusApiComfyuiStatusGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SystemStatsResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/comfyui/status`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SystemStatsResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get ComfyUI system stats (GPU, RAM, etc.).
   * Comfyui Status
   */
  async comfyuiStatusApiComfyuiStatusGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SystemStatsResponse> {
    const response = await this.comfyuiStatusApiComfyuiStatusGetRaw(initOverrides)
    return await response.value()
  }

  /**
   * Queue an arbitrary ComfyUI workflow for execution.  The workflow should be in ComfyUI API format (exported via \"Save (API Format)\"). This endpoint queues the workflow and returns immediately with the prompt_id. Use /history/{prompt_id} to check the result.
   * Comfyui Workflow
   */
  async comfyuiWorkflowApiComfyuiWorkflowPostRaw(
    requestParameters: ComfyuiWorkflowApiComfyuiWorkflowPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<WorkflowResponse>> {
    if (requestParameters['workflowRequest'] == null) {
      throw new runtime.RequiredError(
        'workflowRequest',
        'Required parameter "workflowRequest" was null or undefined when calling comfyuiWorkflowApiComfyuiWorkflowPost().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/comfyui/workflow`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: WorkflowRequestToJSON(requestParameters['workflowRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowResponseFromJSON(jsonValue))
  }

  /**
   * Queue an arbitrary ComfyUI workflow for execution.  The workflow should be in ComfyUI API format (exported via \"Save (API Format)\"). This endpoint queues the workflow and returns immediately with the prompt_id. Use /history/{prompt_id} to check the result.
   * Comfyui Workflow
   */
  async comfyuiWorkflowApiComfyuiWorkflowPost(
    requestParameters: ComfyuiWorkflowApiComfyuiWorkflowPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<WorkflowResponse> {
    const response = await this.comfyuiWorkflowApiComfyuiWorkflowPostRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }
}
