/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.16
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DownloadRequest, HTTPValidationError } from '../models/index'
import {
  DownloadRequestFromJSON,
  DownloadRequestToJSON,
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface GetDownloadStatusApiDownloadStatusDownloadIdGetRequest {
  downloadId: string
}

export interface StartDownloadApiDownloadPostRequest {
  downloadRequest: DownloadRequest
}

/**
 *
 */
export class DownloadApi extends runtime.BaseAPI {
  /**
   * Get status of a download.
   * Get Download Status
   */
  async getDownloadStatusApiDownloadStatusDownloadIdGetRaw(
    requestParameters: GetDownloadStatusApiDownloadStatusDownloadIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    if (requestParameters['downloadId'] == null) {
      throw new runtime.RequiredError(
        'downloadId',
        'Required parameter "downloadId" was null or undefined when calling getDownloadStatusApiDownloadStatusDownloadIdGet().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    let urlPath = `/api/download/status/{download_id}`
    urlPath = urlPath.replace(
      `{${'download_id'}}`,
      encodeURIComponent(String(requestParameters['downloadId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Get status of a download.
   * Get Download Status
   */
  async getDownloadStatusApiDownloadStatusDownloadIdGet(
    requestParameters: GetDownloadStatusApiDownloadStatusDownloadIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.getDownloadStatusApiDownloadStatusDownloadIdGetRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * List all active/recent downloads.
   * List Active Downloads
   */
  async listActiveDownloadsApiDownloadActiveGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/download/active`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * List all active/recent downloads.
   * List Active Downloads
   */
  async listActiveDownloadsApiDownloadActiveGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.listActiveDownloadsApiDownloadActiveGetRaw(initOverrides)
    return await response.value()
  }

  /**
   * Start a model download (async with progress tracking).
   * Start Download
   */
  async startDownloadApiDownloadPostRaw(
    requestParameters: StartDownloadApiDownloadPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    if (requestParameters['downloadRequest'] == null) {
      throw new runtime.RequiredError(
        'downloadRequest',
        'Required parameter "downloadRequest" was null or undefined when calling startDownloadApiDownloadPost().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/download`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: DownloadRequestToJSON(requestParameters['downloadRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Start a model download (async with progress tracking).
   * Start Download
   */
  async startDownloadApiDownloadPost(
    requestParameters: StartDownloadApiDownloadPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.startDownloadApiDownloadPostRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
