/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HTTPValidationError, MetadataUpdate } from '../models/index'
import {
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
  MetadataUpdateFromJSON,
  MetadataUpdateToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface DeleteImageApiImagesImageIdDeleteRequest {
  imageId: string
}

export interface EditImageMetadataApiImagesImageIdEditPostRequest {
  imageId: string
  metadataUpdate: MetadataUpdate
}

export interface GetImageApiImagesImageIdGetRequest {
  imageId: string
}

export interface GetImageMetadataApiImagesImageIdMetaGetRequest {
  imageId: string
}

export interface ListImagesApiImagesGetRequest {
  limit?: number
  offset?: number
  newestFirst?: boolean
}

/**
 *
 */
export class GalleryApi extends runtime.BaseAPI {
  /**
   * Delete an image and its metadata.
   * Delete Image
   */
  async deleteImageApiImagesImageIdDeleteRaw(
    requestParameters: DeleteImageApiImagesImageIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    if (requestParameters['imageId'] == null) {
      throw new runtime.RequiredError(
        'imageId',
        'Required parameter "imageId" was null or undefined when calling deleteImageApiImagesImageIdDelete().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    let urlPath = `/api/images/{image_id}`
    urlPath = urlPath.replace(
      `{${'image_id'}}`,
      encodeURIComponent(String(requestParameters['imageId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Delete an image and its metadata.
   * Delete Image
   */
  async deleteImageApiImagesImageIdDelete(
    requestParameters: DeleteImageApiImagesImageIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.deleteImageApiImagesImageIdDeleteRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Update metadata for an image.
   * Edit Image Metadata
   */
  async editImageMetadataApiImagesImageIdEditPostRaw(
    requestParameters: EditImageMetadataApiImagesImageIdEditPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    if (requestParameters['imageId'] == null) {
      throw new runtime.RequiredError(
        'imageId',
        'Required parameter "imageId" was null or undefined when calling editImageMetadataApiImagesImageIdEditPost().',
      )
    }

    if (requestParameters['metadataUpdate'] == null) {
      throw new runtime.RequiredError(
        'metadataUpdate',
        'Required parameter "metadataUpdate" was null or undefined when calling editImageMetadataApiImagesImageIdEditPost().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    let urlPath = `/api/images/{image_id}/edit`
    urlPath = urlPath.replace(
      `{${'image_id'}}`,
      encodeURIComponent(String(requestParameters['imageId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: MetadataUpdateToJSON(requestParameters['metadataUpdate']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Update metadata for an image.
   * Edit Image Metadata
   */
  async editImageMetadataApiImagesImageIdEditPost(
    requestParameters: EditImageMetadataApiImagesImageIdEditPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.editImageMetadataApiImagesImageIdEditPostRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Get gallery statistics.
   * Gallery Stats
   */
  async galleryStatsApiImagesStatsSummaryGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/images/stats/summary`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Get gallery statistics.
   * Gallery Stats
   */
  async galleryStatsApiImagesStatsSummaryGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.galleryStatsApiImagesStatsSummaryGetRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get an image file by ID.
   * Get Image
   */
  async getImageApiImagesImageIdGetRaw(
    requestParameters: GetImageApiImagesImageIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['imageId'] == null) {
      throw new runtime.RequiredError(
        'imageId',
        'Required parameter "imageId" was null or undefined when calling getImageApiImagesImageIdGet().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    let urlPath = `/api/images/{image_id}`
    urlPath = urlPath.replace(
      `{${'image_id'}}`,
      encodeURIComponent(String(requestParameters['imageId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Get an image file by ID.
   * Get Image
   */
  async getImageApiImagesImageIdGet(
    requestParameters: GetImageApiImagesImageIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.getImageApiImagesImageIdGetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get metadata for an image.
   * Get Image Metadata
   */
  async getImageMetadataApiImagesImageIdMetaGetRaw(
    requestParameters: GetImageMetadataApiImagesImageIdMetaGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    if (requestParameters['imageId'] == null) {
      throw new runtime.RequiredError(
        'imageId',
        'Required parameter "imageId" was null or undefined when calling getImageMetadataApiImagesImageIdMetaGet().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    let urlPath = `/api/images/{image_id}/meta`
    urlPath = urlPath.replace(
      `{${'image_id'}}`,
      encodeURIComponent(String(requestParameters['imageId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Get metadata for an image.
   * Get Image Metadata
   */
  async getImageMetadataApiImagesImageIdMetaGet(
    requestParameters: GetImageMetadataApiImagesImageIdMetaGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.getImageMetadataApiImagesImageIdMetaGetRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * List images in the gallery, paginated.
   * List Images
   */
  async listImagesApiImagesGetRaw(
    requestParameters: ListImagesApiImagesGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    const queryParameters: any = {}

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset']
    }

    if (requestParameters['newestFirst'] != null) {
      queryParameters['newest_first'] = requestParameters['newestFirst']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/images`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * List images in the gallery, paginated.
   * List Images
   */
  async listImagesApiImagesGet(
    requestParameters: ListImagesApiImagesGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.listImagesApiImagesGetRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
