/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HTTPValidationError, Provider, SortOrder } from '../models/index'
import {
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
  ProviderFromJSON,
  ProviderToJSON,
  SortOrderFromJSON,
  SortOrderToJSON,
} from '../models/index'
import * as runtime from '../runtime'

export interface SearchModelsApiSearchGetRequest {
  query?: string | null
  provider?: Provider
  types?: string | null
  baseModels?: string | null
  period?: string | null
  nsfw?: string | null
  sfw?: boolean
  commercial?: string | null
  page?: number | null
  pipeline?: string | null
  sort?: SortOrder
  limit?: number
  tag?: string | null
  author?: string | null
}

/**
 *
 */
export class SearchApi extends runtime.BaseAPI {
  /**
   * Search models across CivitAI and/or Hugging Face.  Returns results from selected provider(s). When provider=all, returns results from both CivitAI and Hugging Face in separate keys.
   * Search Models
   */
  async searchModelsApiSearchGetRaw(
    requestParameters: SearchModelsApiSearchGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    const queryParameters: any = {}

    if (requestParameters['query'] != null) {
      queryParameters['query'] = requestParameters['query']
    }

    if (requestParameters['provider'] != null) {
      queryParameters['provider'] = requestParameters['provider']
    }

    if (requestParameters['types'] != null) {
      queryParameters['types'] = requestParameters['types']
    }

    if (requestParameters['baseModels'] != null) {
      queryParameters['baseModels'] = requestParameters['baseModels']
    }

    if (requestParameters['period'] != null) {
      queryParameters['period'] = requestParameters['period']
    }

    if (requestParameters['nsfw'] != null) {
      queryParameters['nsfw'] = requestParameters['nsfw']
    }

    if (requestParameters['sfw'] != null) {
      queryParameters['sfw'] = requestParameters['sfw']
    }

    if (requestParameters['commercial'] != null) {
      queryParameters['commercial'] = requestParameters['commercial']
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['pipeline'] != null) {
      queryParameters['pipeline'] = requestParameters['pipeline']
    }

    if (requestParameters['sort'] != null) {
      queryParameters['sort'] = requestParameters['sort']
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    if (requestParameters['tag'] != null) {
      queryParameters['tag'] = requestParameters['tag']
    }

    if (requestParameters['author'] != null) {
      queryParameters['author'] = requestParameters['author']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['X-API-Key'] = await this.configuration.apiKey('X-API-Key') // APIKeyHeader authentication
    }

    if (this.configuration && this.configuration.apiKey) {
      queryParameters['api_key'] = await this.configuration.apiKey('api_key') // APIKeyQuery authentication
    }

    const urlPath = `/api/search`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Search models across CivitAI and/or Hugging Face.  Returns results from selected provider(s). When provider=all, returns results from both CivitAI and Hugging Face in separate keys.
   * Search Models
   */
  async searchModelsApiSearchGet(
    requestParameters: SearchModelsApiSearchGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.searchModelsApiSearchGetRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
