/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Request body for caching a model.
 * @export
 * @interface CacheRequest
 */
export interface CacheRequest {
  /**
   *
   * @type {number}
   * @memberof CacheRequest
   */
  modelId: number
}

/**
 * Check if a given object implements the CacheRequest interface.
 */
export function instanceOfCacheRequest(value: object): value is CacheRequest {
  if (!('modelId' in value) || value['modelId'] === undefined) return false
  return true
}

export function CacheRequestFromJSON(json: any): CacheRequest {
  return CacheRequestFromJSONTyped(json, false)
}

export function CacheRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheRequest {
  if (json == null) {
    return json
  }
  return {
    modelId: json['model_id'],
  }
}

export function CacheRequestToJSON(json: any): CacheRequest {
  return CacheRequestToJSONTyped(json, false)
}

export function CacheRequestToJSONTyped(
  value?: CacheRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    model_id: value['modelId'],
  }
}
