/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.16
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Commercial use filter options.
 * @export
 */
export const CommercialUse = {
  None: 'None',
  Image: 'Image',
  Rent: 'Rent',
  Sell: 'Sell',
} as const
export type CommercialUse = (typeof CommercialUse)[keyof typeof CommercialUse]

export function instanceOfCommercialUse(value: any): boolean {
  for (const key in CommercialUse) {
    if (Object.hasOwn(CommercialUse, key)) {
      if (CommercialUse[key as keyof typeof CommercialUse] === value) {
        return true
      }
    }
  }
  return false
}

export function CommercialUseFromJSON(json: any): CommercialUse {
  return CommercialUseFromJSONTyped(json, false)
}

export function CommercialUseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialUse {
  return json as CommercialUse
}

export function CommercialUseToJSON(value?: CommercialUse | null): any {
  return value as any
}

export function CommercialUseToJSONTyped(value: any, ignoreDiscriminator: boolean): CommercialUse {
  return value as CommercialUse
}
