/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.16
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Request body for downloading a model.
 * @export
 * @interface DownloadRequest
 */
export interface DownloadRequest {
  /**
   *
   * @type {number}
   * @memberof DownloadRequest
   */
  versionId?: number | null
  /**
   *
   * @type {number}
   * @memberof DownloadRequest
   */
  modelId?: number | null
  /**
   *
   * @type {string}
   * @memberof DownloadRequest
   */
  hash?: string | null
  /**
   *
   * @type {string}
   * @memberof DownloadRequest
   */
  outputDir?: string | null
}

/**
 * Check if a given object implements the DownloadRequest interface.
 */
export function instanceOfDownloadRequest(value: object): value is DownloadRequest {
  return true
}

export function DownloadRequestFromJSON(json: any): DownloadRequest {
  return DownloadRequestFromJSONTyped(json, false)
}

export function DownloadRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DownloadRequest {
  if (json == null) {
    return json
  }
  return {
    versionId: json['version_id'] == null ? undefined : json['version_id'],
    modelId: json['model_id'] == null ? undefined : json['model_id'],
    hash: json['hash'] == null ? undefined : json['hash'],
    outputDir: json['output_dir'] == null ? undefined : json['output_dir'],
  }
}

export function DownloadRequestToJSON(json: any): DownloadRequest {
  return DownloadRequestToJSONTyped(json, false)
}

export function DownloadRequestToJSONTyped(
  value?: DownloadRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    version_id: value['versionId'],
    model_id: value['modelId'],
    hash: value['hash'],
    output_dir: value['outputDir'],
  }
}
