/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Request body for text-to-image generation.
 * @export
 * @interface GenerateRequest
 */
export interface GenerateRequest {
  /**
   * Positive prompt text
   * @type {string}
   * @memberof GenerateRequest
   */
  prompt: string
  /**
   * Negative prompt text
   * @type {string}
   * @memberof GenerateRequest
   */
  negativePrompt?: string
  /**
   *
   * @type {string}
   * @memberof GenerateRequest
   */
  model?: string | null
  /**
   * Image width
   * @type {number}
   * @memberof GenerateRequest
   */
  width?: number
  /**
   * Image height
   * @type {number}
   * @memberof GenerateRequest
   */
  height?: number
  /**
   * Sampling steps
   * @type {number}
   * @memberof GenerateRequest
   */
  steps?: number
  /**
   * CFG scale
   * @type {number}
   * @memberof GenerateRequest
   */
  cfg?: number
  /**
   * Random seed (-1 for random)
   * @type {number}
   * @memberof GenerateRequest
   */
  seed?: number
  /**
   * Sampler name
   * @type {string}
   * @memberof GenerateRequest
   */
  sampler?: string
  /**
   * Scheduler name
   * @type {string}
   * @memberof GenerateRequest
   */
  scheduler?: string
}

/**
 * Check if a given object implements the GenerateRequest interface.
 */
export function instanceOfGenerateRequest(value: object): value is GenerateRequest {
  if (!('prompt' in value) || value['prompt'] === undefined) return false
  return true
}

export function GenerateRequestFromJSON(json: any): GenerateRequest {
  return GenerateRequestFromJSONTyped(json, false)
}

export function GenerateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GenerateRequest {
  if (json == null) {
    return json
  }
  return {
    prompt: json['prompt'],
    negativePrompt: json['negative_prompt'] == null ? undefined : json['negative_prompt'],
    model: json['model'] == null ? undefined : json['model'],
    width: json['width'] == null ? undefined : json['width'],
    height: json['height'] == null ? undefined : json['height'],
    steps: json['steps'] == null ? undefined : json['steps'],
    cfg: json['cfg'] == null ? undefined : json['cfg'],
    seed: json['seed'] == null ? undefined : json['seed'],
    sampler: json['sampler'] == null ? undefined : json['sampler'],
    scheduler: json['scheduler'] == null ? undefined : json['scheduler'],
  }
}

export function GenerateRequestToJSON(json: any): GenerateRequest {
  return GenerateRequestToJSONTyped(json, false)
}

export function GenerateRequestToJSONTyped(
  value?: GenerateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    prompt: value['prompt'],
    negative_prompt: value['negativePrompt'],
    model: value['model'],
    width: value['width'],
    height: value['height'],
    steps: value['steps'],
    cfg: value['cfg'],
    seed: value['seed'],
    sampler: value['sampler'],
    scheduler: value['scheduler'],
  }
}
