/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Response from text-to-image generation.
 * @export
 * @interface GenerateResponse
 */
export interface GenerateResponse {
  /**
   *
   * @type {boolean}
   * @memberof GenerateResponse
   */
  success: boolean
  /**
   *
   * @type {string}
   * @memberof GenerateResponse
   */
  promptId: string
  /**
   *
   * @type {Array<string>}
   * @memberof GenerateResponse
   */
  images?: Array<string>
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof GenerateResponse
   */
  errors?: { [key: string]: any }
}

/**
 * Check if a given object implements the GenerateResponse interface.
 */
export function instanceOfGenerateResponse(value: object): value is GenerateResponse {
  if (!('success' in value) || value['success'] === undefined) return false
  if (!('promptId' in value) || value['promptId'] === undefined) return false
  return true
}

export function GenerateResponseFromJSON(json: any): GenerateResponse {
  return GenerateResponseFromJSONTyped(json, false)
}

export function GenerateResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GenerateResponse {
  if (json == null) {
    return json
  }
  return {
    success: json['success'],
    promptId: json['prompt_id'],
    images: json['images'] == null ? undefined : json['images'],
    errors: json['errors'] == null ? undefined : json['errors'],
  }
}

export function GenerateResponseToJSON(json: any): GenerateResponse {
  return GenerateResponseToJSONTyped(json, false)
}

export function GenerateResponseToJSONTyped(
  value?: GenerateResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    success: value['success'],
    prompt_id: value['promptId'],
    images: value['images'],
    errors: value['errors'],
  }
}
