/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.16
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Request body for updating image metadata.
 * @export
 * @interface MetadataUpdate
 */
export interface MetadataUpdate {
  /**
   *
   * @type {Array<string>}
   * @memberof MetadataUpdate
   */
  tags?: Array<string> | null
  /**
   *
   * @type {string}
   * @memberof MetadataUpdate
   */
  notes?: string | null
  /**
   *
   * @type {number}
   * @memberof MetadataUpdate
   */
  rating?: number | null
  /**
   *
   * @type {boolean}
   * @memberof MetadataUpdate
   */
  favorite?: boolean | null
}

/**
 * Check if a given object implements the MetadataUpdate interface.
 */
export function instanceOfMetadataUpdate(value: object): value is MetadataUpdate {
  return true
}

export function MetadataUpdateFromJSON(json: any): MetadataUpdate {
  return MetadataUpdateFromJSONTyped(json, false)
}

export function MetadataUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MetadataUpdate {
  if (json == null) {
    return json
  }
  return {
    tags: json['tags'] == null ? undefined : json['tags'],
    notes: json['notes'] == null ? undefined : json['notes'],
    rating: json['rating'] == null ? undefined : json['rating'],
    favorite: json['favorite'] == null ? undefined : json['favorite'],
  }
}

export function MetadataUpdateToJSON(json: any): MetadataUpdate {
  return MetadataUpdateToJSONTyped(json, false)
}

export function MetadataUpdateToJSONTyped(
  value?: MetadataUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    tags: value['tags'],
    notes: value['notes'],
    rating: value['rating'],
    favorite: value['favorite'],
  }
}
