/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Available models response.
 * @export
 * @interface ModelsResponse
 */
export interface ModelsResponse {
  /**
   *
   * @type {Array<string>}
   * @memberof ModelsResponse
   */
  checkpoints?: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof ModelsResponse
   */
  loras?: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof ModelsResponse
   */
  vae?: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof ModelsResponse
   */
  clip?: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof ModelsResponse
   */
  controlnet?: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof ModelsResponse
   */
  upscaleModels?: Array<string>
}

/**
 * Check if a given object implements the ModelsResponse interface.
 */
export function instanceOfModelsResponse(value: object): value is ModelsResponse {
  return true
}

export function ModelsResponseFromJSON(json: any): ModelsResponse {
  return ModelsResponseFromJSONTyped(json, false)
}

export function ModelsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ModelsResponse {
  if (json == null) {
    return json
  }
  return {
    checkpoints: json['checkpoints'] == null ? undefined : json['checkpoints'],
    loras: json['loras'] == null ? undefined : json['loras'],
    vae: json['vae'] == null ? undefined : json['vae'],
    clip: json['clip'] == null ? undefined : json['clip'],
    controlnet: json['controlnet'] == null ? undefined : json['controlnet'],
    upscaleModels: json['upscale_models'] == null ? undefined : json['upscale_models'],
  }
}

export function ModelsResponseToJSON(json: any): ModelsResponse {
  return ModelsResponseToJSONTyped(json, false)
}

export function ModelsResponseToJSONTyped(
  value?: ModelsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    checkpoints: value['checkpoints'],
    loras: value['loras'],
    vae: value['vae'],
    clip: value['clip'],
    controlnet: value['controlnet'],
    upscale_models: value['upscaleModels'],
  }
}
