/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NSFW content filter levels.
 * @export
 */
export const NsfwLevel = {
  None: 'None',
  Soft: 'Soft',
  Mature: 'Mature',
  X: 'X',
} as const
export type NsfwLevel = (typeof NsfwLevel)[keyof typeof NsfwLevel]

export function instanceOfNsfwLevel(value: any): boolean {
  for (const key in NsfwLevel) {
    if (Object.hasOwn(NsfwLevel, key)) {
      if (NsfwLevel[key as keyof typeof NsfwLevel] === value) {
        return true
      }
    }
  }
  return false
}

export function NsfwLevelFromJSON(json: any): NsfwLevel {
  return NsfwLevelFromJSONTyped(json, false)
}

export function NsfwLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NsfwLevel {
  return json as NsfwLevel
}

export function NsfwLevelToJSON(value?: NsfwLevel | null): any {
  return value as any
}

export function NsfwLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): NsfwLevel {
  return value as NsfwLevel
}
