/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.16
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Time period filter options.
 * @export
 */
export const Period = {
  AllTime: 'AllTime',
  Year: 'Year',
  Month: 'Month',
  Week: 'Week',
  Day: 'Day',
} as const
export type Period = (typeof Period)[keyof typeof Period]

export function instanceOfPeriod(value: any): boolean {
  for (const key in Period) {
    if (Object.hasOwn(Period, key)) {
      if (Period[key as keyof typeof Period] === value) {
        return true
      }
    }
  }
  return false
}

export function PeriodFromJSON(json: any): Period {
  return PeriodFromJSONTyped(json, false)
}

export function PeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Period {
  return json as Period
}

export function PeriodToJSON(value?: Period | null): any {
  return value as any
}

export function PeriodToJSONTyped(value: any, ignoreDiscriminator: boolean): Period {
  return value as Period
}
