/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Search provider options.
 * @export
 */
export const Provider = {
  Civitai: 'civitai',
  Hf: 'hf',
  All: 'all',
} as const
export type Provider = (typeof Provider)[keyof typeof Provider]

export function instanceOfProvider(value: any): boolean {
  for (const key in Provider) {
    if (Object.hasOwn(Provider, key)) {
      if (Provider[key as keyof typeof Provider] === value) {
        return true
      }
    }
  }
  return false
}

export function ProviderFromJSON(json: any): Provider {
  return ProviderFromJSONTyped(json, false)
}

export function ProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Provider {
  return json as Provider
}

export function ProviderToJSON(value?: Provider | null): any {
  return value as any
}

export function ProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): Provider {
  return value as Provider
}
