/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Queue status response.
 * @export
 * @interface QueueStatusResponse
 */
export interface QueueStatusResponse {
  /**
   *
   * @type {Array<any>}
   * @memberof QueueStatusResponse
   */
  queueRunning?: Array<any>
  /**
   *
   * @type {Array<any>}
   * @memberof QueueStatusResponse
   */
  queuePending?: Array<any>
}

/**
 * Check if a given object implements the QueueStatusResponse interface.
 */
export function instanceOfQueueStatusResponse(value: object): value is QueueStatusResponse {
  return true
}

export function QueueStatusResponseFromJSON(json: any): QueueStatusResponse {
  return QueueStatusResponseFromJSONTyped(json, false)
}

export function QueueStatusResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QueueStatusResponse {
  if (json == null) {
    return json
  }
  return {
    queueRunning: json['queue_running'] == null ? undefined : json['queue_running'],
    queuePending: json['queue_pending'] == null ? undefined : json['queue_pending'],
  }
}

export function QueueStatusResponseToJSON(json: any): QueueStatusResponse {
  return QueueStatusResponseToJSONTyped(json, false)
}

export function QueueStatusResponseToJSONTyped(
  value?: QueueStatusResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    queue_running: value['queueRunning'],
    queue_pending: value['queuePending'],
  }
}
