/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Request body for directory scan.
 * @export
 * @interface ScanRequest
 */
export interface ScanRequest {
  /**
   *
   * @type {string}
   * @memberof ScanRequest
   */
  directory: string
}

/**
 * Check if a given object implements the ScanRequest interface.
 */
export function instanceOfScanRequest(value: object): value is ScanRequest {
  if (!('directory' in value) || value['directory'] === undefined) return false
  return true
}

export function ScanRequestFromJSON(json: any): ScanRequest {
  return ScanRequestFromJSONTyped(json, false)
}

export function ScanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanRequest {
  if (json == null) {
    return json
  }
  return {
    directory: json['directory'],
  }
}

export function ScanRequestToJSON(json: any): ScanRequest {
  return ScanRequestToJSONTyped(json, false)
}

export function ScanRequestToJSONTyped(
  value?: ScanRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    directory: value['directory'],
  }
}
