/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Sort order options.
 * @export
 */
export const SortOrder = {
  Downloads: 'downloads',
  Rating: 'rating',
  Newest: 'newest',
} as const
export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]

export function instanceOfSortOrder(value: any): boolean {
  for (const key in SortOrder) {
    if (Object.hasOwn(SortOrder, key)) {
      if (SortOrder[key as keyof typeof SortOrder] === value) {
        return true
      }
    }
  }
  return false
}

export function SortOrderFromJSON(json: any): SortOrder {
  return SortOrderFromJSONTyped(json, false)
}

export function SortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortOrder {
  return json as SortOrder
}

export function SortOrderToJSON(value?: SortOrder | null): any {
  return value as any
}

export function SortOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): SortOrder {
  return value as SortOrder
}
