/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * System stats response.
 * @export
 * @interface SystemStatsResponse
 */
export interface SystemStatsResponse {
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof SystemStatsResponse
   */
  system?: { [key: string]: any }
  /**
   *
   * @type {Array<{ [key: string]: any; }>}
   * @memberof SystemStatsResponse
   */
  devices?: Array<{ [key: string]: any }>
}

/**
 * Check if a given object implements the SystemStatsResponse interface.
 */
export function instanceOfSystemStatsResponse(value: object): value is SystemStatsResponse {
  return true
}

export function SystemStatsResponseFromJSON(json: any): SystemStatsResponse {
  return SystemStatsResponseFromJSONTyped(json, false)
}

export function SystemStatsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SystemStatsResponse {
  if (json == null) {
    return json
  }
  return {
    system: json['system'] == null ? undefined : json['system'],
    devices: json['devices'] == null ? undefined : json['devices'],
  }
}

export function SystemStatsResponseToJSON(json: any): SystemStatsResponse {
  return SystemStatsResponseToJSONTyped(json, false)
}

export function SystemStatsResponseToJSONTyped(
  value?: SystemStatsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    system: value['system'],
    devices: value['devices'],
  }
}
