/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Sort order options.
 * @export
 */
export const TensorsServerSearchRoutesSortOrder = {
  Downloads: 'downloads',
  Rating: 'rating',
  Newest: 'newest',
} as const
export type TensorsServerSearchRoutesSortOrder =
  (typeof TensorsServerSearchRoutesSortOrder)[keyof typeof TensorsServerSearchRoutesSortOrder]

export function instanceOfTensorsServerSearchRoutesSortOrder(value: any): boolean {
  for (const key in TensorsServerSearchRoutesSortOrder) {
    if (Object.hasOwn(TensorsServerSearchRoutesSortOrder, key)) {
      if (
        TensorsServerSearchRoutesSortOrder[
          key as keyof typeof TensorsServerSearchRoutesSortOrder
        ] === value
      ) {
        return true
      }
    }
  }
  return false
}

export function TensorsServerSearchRoutesSortOrderFromJSON(
  json: any,
): TensorsServerSearchRoutesSortOrder {
  return TensorsServerSearchRoutesSortOrderFromJSONTyped(json, false)
}

export function TensorsServerSearchRoutesSortOrderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TensorsServerSearchRoutesSortOrder {
  return json as TensorsServerSearchRoutesSortOrder
}

export function TensorsServerSearchRoutesSortOrderToJSON(
  value?: TensorsServerSearchRoutesSortOrder | null,
): any {
  return value as any
}

export function TensorsServerSearchRoutesSortOrderToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): TensorsServerSearchRoutesSortOrder {
  return value as TensorsServerSearchRoutesSortOrder
}
