/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Sort order options for CivitAI search.
 * @export
 */
export const TensorsServerCivitaiRoutesSortOrder = {
  MostDownloaded: 'Most Downloaded',
  HighestRated: 'Highest Rated',
  Newest: 'Newest',
} as const
export type TensorsServerCivitaiRoutesSortOrder =
  (typeof TensorsServerCivitaiRoutesSortOrder)[keyof typeof TensorsServerCivitaiRoutesSortOrder]

export function instanceOfTensorsServerCivitaiRoutesSortOrder(value: any): boolean {
  for (const key in TensorsServerCivitaiRoutesSortOrder) {
    if (Object.hasOwn(TensorsServerCivitaiRoutesSortOrder, key)) {
      if (
        TensorsServerCivitaiRoutesSortOrder[
          key as keyof typeof TensorsServerCivitaiRoutesSortOrder
        ] === value
      ) {
        return true
      }
    }
  }
  return false
}

export function TensorsServerCivitaiRoutesSortOrderFromJSON(
  json: any,
): TensorsServerCivitaiRoutesSortOrder {
  return TensorsServerCivitaiRoutesSortOrderFromJSONTyped(json, false)
}

export function TensorsServerCivitaiRoutesSortOrderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TensorsServerCivitaiRoutesSortOrder {
  return json as TensorsServerCivitaiRoutesSortOrder
}

export function TensorsServerCivitaiRoutesSortOrderToJSON(
  value?: TensorsServerCivitaiRoutesSortOrder | null,
): any {
  return value as any
}

export function TensorsServerCivitaiRoutesSortOrderToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): TensorsServerCivitaiRoutesSortOrder {
  return value as TensorsServerCivitaiRoutesSortOrder
}
