/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Response from workflow execution.
 * @export
 * @interface WorkflowResponse
 */
export interface WorkflowResponse {
  /**
   *
   * @type {boolean}
   * @memberof WorkflowResponse
   */
  success: boolean
  /**
   *
   * @type {string}
   * @memberof WorkflowResponse
   */
  promptId: string
  /**
   *
   * @type {number}
   * @memberof WorkflowResponse
   */
  number?: number | null
  /**
   *
   * @type {string}
   * @memberof WorkflowResponse
   */
  error?: string | null
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof WorkflowResponse
   */
  nodeErrors?: { [key: string]: any }
}

/**
 * Check if a given object implements the WorkflowResponse interface.
 */
export function instanceOfWorkflowResponse(value: object): value is WorkflowResponse {
  if (!('success' in value) || value['success'] === undefined) return false
  if (!('promptId' in value) || value['promptId'] === undefined) return false
  return true
}

export function WorkflowResponseFromJSON(json: any): WorkflowResponse {
  return WorkflowResponseFromJSONTyped(json, false)
}

export function WorkflowResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkflowResponse {
  if (json == null) {
    return json
  }
  return {
    success: json['success'],
    promptId: json['prompt_id'],
    number: json['number'] == null ? undefined : json['number'],
    error: json['error'] == null ? undefined : json['error'],
    nodeErrors: json['node_errors'] == null ? undefined : json['node_errors'],
  }
}

export function WorkflowResponseToJSON(json: any): WorkflowResponse {
  return WorkflowResponseToJSONTyped(json, false)
}

export function WorkflowResponseToJSONTyped(
  value?: WorkflowResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    success: value['success'],
    prompt_id: value['promptId'],
    number: value['number'],
    error: value['error'],
    node_errors: value['nodeErrors'],
  }
}
