/* tslint:disable */
/* eslint-disable */
/**
 * tensors
 * API for CivitAI model management and image gallery
 *
 * The version of the OpenAPI document: 0.1.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Request body for running arbitrary workflow.
 * @export
 * @interface WorkflowRequest
 */
export interface WorkflowRequest {
  /**
   * ComfyUI API-format workflow
   * @type {{ [key: string]: any; }}
   * @memberof WorkflowRequest
   */
  workflow: { [key: string]: any }
}

/**
 * Check if a given object implements the WorkflowRequest interface.
 */
export function instanceOfWorkflowRequest(value: object): value is WorkflowRequest {
  if (!('workflow' in value) || value['workflow'] === undefined) return false
  return true
}

export function WorkflowRequestFromJSON(json: any): WorkflowRequest {
  return WorkflowRequestFromJSONTyped(json, false)
}

export function WorkflowRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkflowRequest {
  if (json == null) {
    return json
  }
  return {
    workflow: json['workflow'],
  }
}

export function WorkflowRequestToJSON(json: any): WorkflowRequest {
  return WorkflowRequestToJSONTyped(json, false)
}

export function WorkflowRequestToJSONTyped(
  value?: WorkflowRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    workflow: value['workflow'],
  }
}
